version: "3.9"

services:
  grafana:
    container_name: "grafana"
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - observability_net
  prometheus:
    container_name: "prometheus"
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - observability_net
  master-exporter:
    container_name: "master-exporter"
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://social-network-local-admin:eephayl3eaph8Xo@master:5432/social-network-local?sslmode=disable"
    links:
      - prometheus
    networks:
      - observability_net
      - social-network_social_network_net

networks:
  observability_net:
    driver: bridge
  social-network_social_network_net:
    external: true