version: '3'
services:
  tarantool:
    image: tarantool/tarantool:2.11.3
    container_name: "tarantool-test"
    command: tarantool /opt/tarantool/init.lua
    networks:
      - tarantool_net_test
    ports:
      - "3302:3301"
    volumes:
      - ./conf/init.lua:/opt/tarantool/init.lua
      - ./conf/config.yml:/etc/tarantool/config.yml
#      - ./tarantool/data:/var/lib/tarantool
    environment:
      TARANTOOL_USER_NAME: admin
      TARANTOOL_USER_PASSWORD: password

networks:
  tarantool_net_test: