logger:
  level: "debug"
  encoding: "console"
  path: "stdout"

public_server:
  enable: true
  endpoint: "localhost"
  port: 8080

admin_server:
  enable: true
  endpoint: "localhost"
  port: 8081

storage:
  hosts:
    - "master"
    - "slave"
  port: 5432
#  database: "postgres"
#  username: "postgres"
  database: "social-network-local"
  username: "social-network-local-admin"
  password: "eepha[l3eaph8Xo"
  ssl_mode: "disable"
  connection_attempts: 3

application:
  app: "social-network"
  salt_value: "xamah6Ael!iat0n"