logger:
  level: "debug"
  encoding: "console"
  path: "stdout"

public_server:
  enable: true
  endpoint: "localhost"
  port: 8080

admin_server:
  enable: true
  endpoint: "localhost"
  port: 8081

storage:
  host: "localhost"
  port: 5432
  database: "social-network-local"
  username: "social-network-local-admin"
  ssl_mode: "disable"
  connection_attempts: 3
