logger:
  level: "debug"
  encoding: "console"
  path: "stdout"
  environment: "prod"

public_server:
  enable: true
  endpoint: "localhost"
  port: 8080

admin_server:
  enable: true
  endpoint: "localhost"
  port: 8081

internal_grpc_server:
  port: 7070
  enable_reflection: true
  enable_recover: true

storage:
  hosts:
    - "master"
#    - "slave"
  port: 5432
  database: "social-network-local"
  username: "social-network-local-admin"
  ssl_mode: "disable"
  connection_attempts: 3

application:
  app: "social-network"
  salt_value: "xamah6Ael!iat0n"

cache:
  enable: true
  address: "redis-cache:6379"
  password: "password"

queue:
  enable: true
  address: "amqp://guest:guest@message-broker:5672"
  queue_name: "snw-queue"
  exchange_name: "events"

notifications_queue:
  enable: true
  address: "amqp://guest:guest@notifications-broker:5672"
  queue_name: "notifications-queue"
  exchange_name: "events"

dialog:
  enable: true
  conn:
    endpoint: dialog-service:7050