logger:
  level: "info"
  environment: "prod"
  encoding: "console"
  path: "stdout"

storage:
  hosts:
    - "localhost"
#    - "slave"
  port: 6432
  database: "social-network-local"
  username: "social-network-local-admin"
  ssl_mode: "disable"
  connection_attempts: 3
  password: "eephayl3eaph8Xo"

application:
  data_file: "people.csv"

tarantool:
  address: "localhost:3301"
  username: "admin"
  password: "password"
