logger:
  level: "debug"
  encoding: "console"
  path: "stdout"

storage:
  hosts:
    - "master"
#    - "slave"
  port: 5432
  database: "social-network-local"
  username: "social-network-local-admin"
  ssl_mode: "disable"
  connection_attempts: 3
